name: Dungeons
main: com.bukkit.mot.dungeons.Dungeons
version: 0.1
commands:
  dungeon:
    description: Allows users to create and play dungeons
  dtool:
    description: Sets the effect of the dungeon edit tool